require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe MailsController do

  # This should return the minimal set of attributes required to create a valid
  # Mail. As you add validations to Mail, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "email" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # MailsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all mails as @mails" do
      mail = Mail.create! valid_attributes
      get :index, {}, valid_session
      assigns(:mails).should eq([mail])
    end
  end

  describe "GET show" do
    it "assigns the requested mail as @mail" do
      mail = Mail.create! valid_attributes
      get :show, {:id => mail.to_param}, valid_session
      assigns(:mail).should eq(mail)
    end
  end

  describe "GET new" do
    it "assigns a new mail as @mail" do
      get :new, {}, valid_session
      assigns(:mail).should be_a_new(Mail)
    end
  end

  describe "GET edit" do
    it "assigns the requested mail as @mail" do
      mail = Mail.create! valid_attributes
      get :edit, {:id => mail.to_param}, valid_session
      assigns(:mail).should eq(mail)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Mail" do
        expect {
          post :create, {:mail => valid_attributes}, valid_session
        }.to change(Mail, :count).by(1)
      end

      it "assigns a newly created mail as @mail" do
        post :create, {:mail => valid_attributes}, valid_session
        assigns(:mail).should be_a(Mail)
        assigns(:mail).should be_persisted
      end

      it "redirects to the created mail" do
        post :create, {:mail => valid_attributes}, valid_session
        response.should redirect_to(Mail.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved mail as @mail" do
        # Trigger the behavior that occurs when invalid params are submitted
        Mail.any_instance.stub(:save).and_return(false)
        post :create, {:mail => { "email" => "invalid value" }}, valid_session
        assigns(:mail).should be_a_new(Mail)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Mail.any_instance.stub(:save).and_return(false)
        post :create, {:mail => { "email" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested mail" do
        mail = Mail.create! valid_attributes
        # Assuming there are no other mails in the database, this
        # specifies that the Mail created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Mail.any_instance.should_receive(:update).with({ "email" => "MyString" })
        put :update, {:id => mail.to_param, :mail => { "email" => "MyString" }}, valid_session
      end

      it "assigns the requested mail as @mail" do
        mail = Mail.create! valid_attributes
        put :update, {:id => mail.to_param, :mail => valid_attributes}, valid_session
        assigns(:mail).should eq(mail)
      end

      it "redirects to the mail" do
        mail = Mail.create! valid_attributes
        put :update, {:id => mail.to_param, :mail => valid_attributes}, valid_session
        response.should redirect_to(mail)
      end
    end

    describe "with invalid params" do
      it "assigns the mail as @mail" do
        mail = Mail.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Mail.any_instance.stub(:save).and_return(false)
        put :update, {:id => mail.to_param, :mail => { "email" => "invalid value" }}, valid_session
        assigns(:mail).should eq(mail)
      end

      it "re-renders the 'edit' template" do
        mail = Mail.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Mail.any_instance.stub(:save).and_return(false)
        put :update, {:id => mail.to_param, :mail => { "email" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested mail" do
      mail = Mail.create! valid_attributes
      expect {
        delete :destroy, {:id => mail.to_param}, valid_session
      }.to change(Mail, :count).by(-1)
    end

    it "redirects to the mails list" do
      mail = Mail.create! valid_attributes
      delete :destroy, {:id => mail.to_param}, valid_session
      response.should redirect_to(mails_url)
    end
  end

end
