require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe RecordEmailsController do

  # This should return the minimal set of attributes required to create a valid
  # RecordEmail. As you add validations to RecordEmail, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "email" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # RecordEmailsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all record_emails as @record_emails" do
      record_email = RecordEmail.create! valid_attributes
      get :index, {}, valid_session
      assigns(:record_emails).should eq([record_email])
    end
  end

  describe "GET show" do
    it "assigns the requested record_email as @record_email" do
      record_email = RecordEmail.create! valid_attributes
      get :show, {:id => record_email.to_param}, valid_session
      assigns(:record_email).should eq(record_email)
    end
  end

  describe "GET new" do
    it "assigns a new record_email as @record_email" do
      get :new, {}, valid_session
      assigns(:record_email).should be_a_new(RecordEmail)
    end
  end

  describe "GET edit" do
    it "assigns the requested record_email as @record_email" do
      record_email = RecordEmail.create! valid_attributes
      get :edit, {:id => record_email.to_param}, valid_session
      assigns(:record_email).should eq(record_email)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new RecordEmail" do
        expect {
          post :create, {:record_email => valid_attributes}, valid_session
        }.to change(RecordEmail, :count).by(1)
      end

      it "assigns a newly created record_email as @record_email" do
        post :create, {:record_email => valid_attributes}, valid_session
        assigns(:record_email).should be_a(RecordEmail)
        assigns(:record_email).should be_persisted
      end

      it "redirects to the created record_email" do
        post :create, {:record_email => valid_attributes}, valid_session
        response.should redirect_to(RecordEmail.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved record_email as @record_email" do
        # Trigger the behavior that occurs when invalid params are submitted
        RecordEmail.any_instance.stub(:save).and_return(false)
        post :create, {:record_email => { "email" => "invalid value" }}, valid_session
        assigns(:record_email).should be_a_new(RecordEmail)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        RecordEmail.any_instance.stub(:save).and_return(false)
        post :create, {:record_email => { "email" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested record_email" do
        record_email = RecordEmail.create! valid_attributes
        # Assuming there are no other record_emails in the database, this
        # specifies that the RecordEmail created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        RecordEmail.any_instance.should_receive(:update).with({ "email" => "MyString" })
        put :update, {:id => record_email.to_param, :record_email => { "email" => "MyString" }}, valid_session
      end

      it "assigns the requested record_email as @record_email" do
        record_email = RecordEmail.create! valid_attributes
        put :update, {:id => record_email.to_param, :record_email => valid_attributes}, valid_session
        assigns(:record_email).should eq(record_email)
      end

      it "redirects to the record_email" do
        record_email = RecordEmail.create! valid_attributes
        put :update, {:id => record_email.to_param, :record_email => valid_attributes}, valid_session
        response.should redirect_to(record_email)
      end
    end

    describe "with invalid params" do
      it "assigns the record_email as @record_email" do
        record_email = RecordEmail.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        RecordEmail.any_instance.stub(:save).and_return(false)
        put :update, {:id => record_email.to_param, :record_email => { "email" => "invalid value" }}, valid_session
        assigns(:record_email).should eq(record_email)
      end

      it "re-renders the 'edit' template" do
        record_email = RecordEmail.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        RecordEmail.any_instance.stub(:save).and_return(false)
        put :update, {:id => record_email.to_param, :record_email => { "email" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested record_email" do
      record_email = RecordEmail.create! valid_attributes
      expect {
        delete :destroy, {:id => record_email.to_param}, valid_session
      }.to change(RecordEmail, :count).by(-1)
    end

    it "redirects to the record_emails list" do
      record_email = RecordEmail.create! valid_attributes
      delete :destroy, {:id => record_email.to_param}, valid_session
      response.should redirect_to(record_emails_url)
    end
  end

end
